# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyyhTWjtrmmT6JMjhvHXOULupnJJcg42
"""

import streamlit as st

# إعداد الصفحة الرئيسية
st.set_page_config(
    page_title="Tech-Muallim | منصة المعلم الذكية",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded"
)

# تخصيص CSS إضافي لضبط الفايب الأحمر والخطوط العربية
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap');

    html, body, [class*="css"] {
        font-family: 'Cairo', sans-serif;
        direction: rtl;
        text-align: right;
    }

    .main-header {
        background: linear-gradient(135deg, #D32F2F 0%, #B71C1C 100%);
        padding: 30px;
        border-radius: 15px;
        color: white;
        text-align: center;
        margin-bottom: 25px;
        box-shadow: 0 4px 15px rgba(211, 47, 47, 0.3);
    }

    .stButton>button {
        background-color: #D32F2F;
        color: white;
        border-radius: 8px;
        border: none;
        padding: 10px 20px;
        font-weight: bold;
        transition: 0.3s;
    }

    .stButton>button:hover {
        background-color: #B71C1C;
        color: white;
    }
    </style>
""", unsafe_allow_html=True)

# واجهة الترحيب في الصفحة الرئيسية
st.markdown("""
    <div class="main-header">
        <h1>🎓 منصة Tech-Muallim الذكية</h1>
        <p>مساعدك الرقمي المتقدم لأتمتة المناهج، تحضير الدروس، وإدارة الصفوف بذكاء</p>
    </div>
""", unsafe_allow_html=True)

st.success("✨ أهلاً بك يا أستاذة أروى في منصتك التعليمية المتكاملة.")
st.markdown("---")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(label="📚 الكتب المرفوعة", value="4 كتب", delta="نشط")

with col2:
    st.metric(label="📝 الحصص المنجزة", value="18 حصة", delta="+3 هذا الأسبوع")

with col3:
    st.metric(label="🎯 نسبة التقدم العام", value="75%", delta="على المسار الصحيح ✅")

st.markdown("### 🧭 التنقل السريع")
st.info("استخدم القائمة الجانبية (Sidebar) للانتقال بين الأقسام المختلفة للمنصة (الخطة والتحضير، المختبر، التقييمات، تحليلات النتائج، وغيرها).")