# -*- coding: utf-8 -*-
"""1_🏠_الرئيسية

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gY9vmbEx5rxTsmA63-D-W3C-C2khm0Dj
"""

import streamlit as st

st.title("🏠 المكتبة الرقمية وأغلفة المناهج الثانوية (مقررات الفيزياء)")
st.markdown("---")

st.markdown("### 📂 اختر مقرر الفيزياء والفصل الدراسي لتفعيل السياق:")

# قائمة مقررات الفيزياء الثانوية المحددة
physics_courses = [
    {"code": "فيز 102", "name": "فيزياء 102"},
    {"code": "فيز 210", "name": "فيزياء 210"},
    {"code": "فيز 217", "name": "فيزياء 217"},
    {"code": "فيز 218", "name": "فيزياء 218"},
    {"code": "فيز 219", "name": "فيزياء 219"}
]

# تقسيم العرض إلى أعمدة لعرض المقررات بشكل مرتب
cols = st.columns(len(physics_courses))

for i, course in enumerate(physics_courses):
    with cols[i]:
        st.markdown(f"### ⚛️ {course['code']}")
        st.write(course['name'])

        # اختيار الفصل الدراسي (الأول أو الثاني) لكل مقرر
        semester = st.selectbox(
            "اختر الفصل الدراسي:",
            ["الفصل الدراسي الأول", "الفصل الدراسي الثاني"],
            key=f"sem_{course['code']}"
        )

        if st.button(f"تفعيل {course['code']}", key=f"btn_{course['code']}"):
            selected_context = f"{course['name']} ({course['code']}) - {semester}"
            st.session_state['selected_book'] = selected_context
            st.success(f"تم تفعيل: {selected_context}")

st.markdown("---")
st.subheader("📤 رفع كتاب خارجي جديد (PDF Upload)")
uploaded_file = st.file_uploader("إذا كان المقرر غير موجود، قم برفع ملف الـ PDF هنا:", type=["pdf"])
if uploaded_file is not None:
    st.success(f"تم رفع الملف '{uploaded_file.name}' بنجاح، جارٍ استخراج الفهرس والمحتوى للمنهج الخارجي...")
    st.session_state['selected_book'] = f"كتاب خارجي: {uploaded_file.name}"